### ISSUE TITLE
GUI without Character

### ISSUE THREAD

**Issue by GeorgeS2019** [gudatr/Godot4CharacterCreator#9]
**Describe the bug**
The GUI loaded, halfway loading the character, the process crashes

**To Reproduce**
- Follow as best as I could to set up, I do not understand every step in the WIKI setup.
- Ideally, there is **a scene to check** if the mesh generation is working before running Character Creator Example

**Expected behavior**
The GUI loaded, halfway loading the character, the process crashes

**Screenshots**

**Desktop (please complete the following information):**
- Windows, Latest Godot 4.2 RC 1

**Comment by gudatr** [comment]
The MeshGeneration was probably not completed as I noted in the discussion. This was most likely caused because the folder blend_shape_data did not exist. With the newest commit it will be created automatically.

**Comment by GeorgeS2019** [comment]
> With the newest commit it will be created automatically.

Do I still follow the WIKI step for setup?

**Comment by GeorgeS2019** [comment]
> Reset the repository using if they are nil or empty.

What does this mean, what is empty??

**Comment by GeorgeS2019** [comment]
Getting error and 

![image](https://github.com/gudatr/Godot4CharacterCreator/assets/49812372/6ee31133-9b8e-4156-9f1e-47df09469cec)

The mesh generation incomplete
![image](https://github.com/gudatr/Godot4CharacterCreator/assets/49812372/3a7e6ba8-3ee1-463a-82ce-8e8bac1852df)

**Comment by gudatr** [comment]
It means the arrays in the previous step, that is now stated explicitly.

Please reset the repository to the latest commit with git reset --hard, as it is mentioned in step 7 and you should be fine.

Also please copy the error message instead of providing a screenshot of about 1% of the message.
Given your git history this behaviour is really dubious.
